{ ... }:
{
  imports = [
    ./alacritty.nix
    ./anki.nix
    ./blender.nix
    ./browser
    ./cursor.nix
    ./discord.nix
    ./feh.nix
    ./games
    ./ghostty
    ./gtkhash.nix
    ./imv.nix
    ./jellyfin-media-player.nix
    ./kitty.nix
    ./mpv
    ./nemo.nix
    ./oculante.nix
    ./qbittorrent.nix
    ./qiv.nix
    ./rio.nix
    ./rofi
    ./slack.nix
    ./stremio.nix
    ./stylix
    ./syncthing.nix
    ./waybar
    ./wezterm
    ./xournalpp.nix
    ./zathura.nix
  ];
}
