# generate new key at ~/.config/sops/age/keys.txt
# $ mkdir -p ~/.config/sops/age
# $ nix shell nixpkgs#age -c age-keygen -o ~/.config/sops/age/keys.txt
#
# Or for root
# # mkdir -p /var/lib/sops-nix/age
# # nix shell nixpkgs#age -c age-keygen -o /var/lib/sops-nix/age/keys.txt
# # chmod go-rwx -R /var/lib/sops-nix/age

# [Optional] generate new key at ~/.config/sops/age/keys.txt from private ssh key at ~/.ssh/private
# $ nix run nixpkgs#ssh-to-age -- -private-key -i ~/.ssh/private > ~/.config/sops/age/keys.txt

# get a public key of ~/.config/sops/age/keys.txt
# nix shell nixpkgs#age -c age-keygen -y ~/.config/sops/age/keys.txt
#
# Or for root
# # nix shell nixpkgs#age -c age-keygen -y /var/lib/sops-nix/age/keys.txt

keys:
  - &primary age17snftqddz8wyf47smg9tfv8xjv2kesj9kq90jvua2vsurtn9nu5sd2xslr
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary
