# generate new key at ~/.config/sops/age/keys.txt
# $ mkdir -p ~/.config/sops/age
# $ nix shell nixpkgs#age -c age-keygen -o ~/.config/sops/age/keys.txt

# [Optional] generate new key at ~/.config/sops/age/keys.txt from private ssh key at ~/.ssh/private
# $ nix run nixpkgs#ssh-to-age -- -private-key -i ~/.ssh/private > ~/.config/sops/age/keys.txt

# get a public key of ~/.config/sops/age/keys.txt
# nix shell nixpkgs#age -c age-keygen -y ~/.config/sops/age/keys.txt

keys:
  - &primary age1c8x77p0ss0w54dtd9dkxnym72nmtf6wg2h587rpn8zd34htj8q6q5m7tnx
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *primary
