{ ... }:
{
  imports = [
    ./aerc
    ./ani-cli.nix
    ./bat.nix
    ./bat.nix
    ./btop.nix
    ./calcurse.nix
    ./dooit.nix
    ./dua.nix
    ./dua.nix
    ./eza.nix
    ./eza.nix
    ./fd.nix
    ./ffmpeg.nix
    ./fselect.nix
    ./fzf.nix
    ./gdb
    ./git
    ./htop.nix
    ./khal.nix
    ./mediainfo.nix
    ./ncmpcpp.nix
    ./neomutt
    ./neovim
    ./newsboat
    ./nvtop.nix
    ./procs.nix
    ./progress.nix
    ./qalculate.nix
    ./silicon.nix
    ./tealdeer.nix
    ./tgpt.nix
    ./tmux.nix
    ./todoist.nix
    ./translate-shell.nix
    ./unar.nix
    ./vim.nix
    ./yazi.nix
    ./yt-dlp.nix
    ./ytfzf.nix
    ./zellij
  ];
}
